### PR TITLE
Fix: turn off lights #33

### PR DESCRIPTION
**Pull request by lightcore-x**

### CODE REVIEW

**Comment by casainho** [comment]
Hi.

Did you test? Are the feature working as expected now?

**Comment by lightcore-x** [comment]
Yes, I've tested it and this fixed the issue.

No not completely it has side effects. Somehow turning on the lights interferes with the motor assistance. See the other issue which I've reported. Don't have a solution for that one yet.

**Comment by casainho** [comment]
Fixed, thanks!!!

**Comment by lightcore-x** [comment]
@casainho But, you didn't merge the changes? Instead you decided to do the changes yourself?

**Comment by casainho** [comment]
Yes because I did understand the issue and did what is supposed to be done, tested and it works.

I do not understand how you did and I don't have the issue you did mention "lights interferes with the motor assistance", so I stick with my changes. I hope is not a problem.

**Pull request closed without merging**
